[package]
name = "esf-wasm"
# Published to npm instead.
publish = false
description = "Library to calculate statistics for EVE Online ship fits"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

# Keeps the file names in the npm package as they were.
[lib]
name = "esf_dogma_engine"
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook.workspace = true
esf-data.workspace = true
esf-dogma-engine = { workspace = true, features = ["typescript"] }
esf-format.workspace = true
tsify.workspace = true
wasm-bindgen.workspace = true
