// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod eve {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_MODIFIER_DOMAIN: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_MODIFIER_DOMAIN: i8 = 6;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_MODIFIER_DOMAIN: [ModifierDomain; 7] = [
  ModifierDomain::ItemID,
  ModifierDomain::ShipID,
  ModifierDomain::CharID,
  ModifierDomain::OtherID,
  ModifierDomain::StructureID,
  ModifierDomain::Target,
  ModifierDomain::TargetID,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ModifierDomain(pub i8);
#[allow(non_upper_case_globals)]
impl ModifierDomain {
  pub const ItemID: Self = Self(0);
  pub const ShipID: Self = Self(1);
  pub const CharID: Self = Self(2);
  pub const OtherID: Self = Self(3);
  pub const StructureID: Self = Self(4);
  pub const Target: Self = Self(5);
  pub const TargetID: Self = Self(6);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 6;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::ItemID,
    Self::ShipID,
    Self::CharID,
    Self::OtherID,
    Self::StructureID,
    Self::Target,
    Self::TargetID,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::ItemID => Some("ItemID"),
      Self::ShipID => Some("ShipID"),
      Self::CharID => Some("CharID"),
      Self::OtherID => Some("OtherID"),
      Self::StructureID => Some("StructureID"),
      Self::Target => Some("Target"),
      Self::TargetID => Some("TargetID"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for ModifierDomain {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for ModifierDomain {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for ModifierDomain {
    type Output = ModifierDomain;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for ModifierDomain {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for ModifierDomain {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for ModifierDomain {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_MODIFIER_FUNC: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_MODIFIER_FUNC: i8 = 5;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_MODIFIER_FUNC: [ModifierFunc; 6] = [
  ModifierFunc::ItemModifier,
  ModifierFunc::LocationGroupModifier,
  ModifierFunc::LocationModifier,
  ModifierFunc::LocationRequiredSkillModifier,
  ModifierFunc::OwnerRequiredSkillModifier,
  ModifierFunc::EffectStopper,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ModifierFunc(pub i8);
#[allow(non_upper_case_globals)]
impl ModifierFunc {
  pub const ItemModifier: Self = Self(0);
  pub const LocationGroupModifier: Self = Self(1);
  pub const LocationModifier: Self = Self(2);
  pub const LocationRequiredSkillModifier: Self = Self(3);
  pub const OwnerRequiredSkillModifier: Self = Self(4);
  pub const EffectStopper: Self = Self(5);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 5;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::ItemModifier,
    Self::LocationGroupModifier,
    Self::LocationModifier,
    Self::LocationRequiredSkillModifier,
    Self::OwnerRequiredSkillModifier,
    Self::EffectStopper,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::ItemModifier => Some("ItemModifier"),
      Self::LocationGroupModifier => Some("LocationGroupModifier"),
      Self::LocationModifier => Some("LocationModifier"),
      Self::LocationRequiredSkillModifier => Some("LocationRequiredSkillModifier"),
      Self::OwnerRequiredSkillModifier => Some("OwnerRequiredSkillModifier"),
      Self::EffectStopper => Some("EffectStopper"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for ModifierFunc {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for ModifierFunc {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for ModifierFunc {
    type Output = ModifierFunc;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for ModifierFunc {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for ModifierFunc {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for ModifierFunc {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_MODIFIER_OPERATION: i8 = -2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_MODIFIER_OPERATION: i8 = 7;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_MODIFIER_OPERATION: [ModifierOperation; 10] = [
  ModifierOperation::Unset,
  ModifierOperation::PreAssign,
  ModifierOperation::PreMul,
  ModifierOperation::PreDiv,
  ModifierOperation::ModAdd,
  ModifierOperation::ModSub,
  ModifierOperation::PostMul,
  ModifierOperation::PostDiv,
  ModifierOperation::PostPercent,
  ModifierOperation::PostAssign,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ModifierOperation(pub i8);
#[allow(non_upper_case_globals)]
impl ModifierOperation {
  pub const Unset: Self = Self(-2);
  pub const PreAssign: Self = Self(-1);
  pub const PreMul: Self = Self(0);
  pub const PreDiv: Self = Self(1);
  pub const ModAdd: Self = Self(2);
  pub const ModSub: Self = Self(3);
  pub const PostMul: Self = Self(4);
  pub const PostDiv: Self = Self(5);
  pub const PostPercent: Self = Self(6);
  pub const PostAssign: Self = Self(7);

  pub const ENUM_MIN: i8 = -2;
  pub const ENUM_MAX: i8 = 7;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Unset,
    Self::PreAssign,
    Self::PreMul,
    Self::PreDiv,
    Self::ModAdd,
    Self::ModSub,
    Self::PostMul,
    Self::PostDiv,
    Self::PostPercent,
    Self::PostAssign,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Unset => Some("Unset"),
      Self::PreAssign => Some("PreAssign"),
      Self::PreMul => Some("PreMul"),
      Self::PreDiv => Some("PreDiv"),
      Self::ModAdd => Some("ModAdd"),
      Self::ModSub => Some("ModSub"),
      Self::PostMul => Some("PostMul"),
      Self::PostDiv => Some("PostDiv"),
      Self::PostPercent => Some("PostPercent"),
      Self::PostAssign => Some("PostAssign"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for ModifierOperation {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for ModifierOperation {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for ModifierOperation {
    type Output = ModifierOperation;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for ModifierOperation {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for ModifierOperation {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for ModifierOperation {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_EFFECT_CATEGORY: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_EFFECT_CATEGORY: i8 = 7;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_EFFECT_CATEGORY: [EffectCategory; 8] = [
  EffectCategory::Passive,
  EffectCategory::Active,
  EffectCategory::Target,
  EffectCategory::Area,
  EffectCategory::Online,
  EffectCategory::Overload,
  EffectCategory::Dungeon,
  EffectCategory::System,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct EffectCategory(pub i8);
#[allow(non_upper_case_globals)]
impl EffectCategory {
  pub const Passive: Self = Self(0);
  pub const Active: Self = Self(1);
  pub const Target: Self = Self(2);
  pub const Area: Self = Self(3);
  pub const Online: Self = Self(4);
  pub const Overload: Self = Self(5);
  pub const Dungeon: Self = Self(6);
  pub const System: Self = Self(7);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 7;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Passive,
    Self::Active,
    Self::Target,
    Self::Area,
    Self::Online,
    Self::Overload,
    Self::Dungeon,
    Self::System,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Passive => Some("Passive"),
      Self::Active => Some("Active"),
      Self::Target => Some("Target"),
      Self::Area => Some("Area"),
      Self::Online => Some("Online"),
      Self::Overload => Some("Overload"),
      Self::Dungeon => Some("Dungeon"),
      Self::System => Some("System"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for EffectCategory {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for EffectCategory {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for EffectCategory {
    type Output = EffectCategory;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for EffectCategory {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for EffectCategory {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for EffectCategory {}
// struct Modifier, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Modifier(pub [u8; 20]);
impl Default for Modifier { 
  fn default() -> Self { 
    Self([0; 20])
  }
}
impl core::fmt::Debug for Modifier {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Modifier")
      .field("domain", &self.domain())
      .field("func", &self.func())
      .field("operation", &self.operation())
      .field("modified_attribute_id", &self.modified_attribute_id())
      .field("modifying_attribute_id", &self.modifying_attribute_id())
      .field("group_id", &self.group_id())
      .field("skill_type_id", &self.skill_type_id())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Modifier {}
impl<'a> flatbuffers::Follow<'a> for Modifier {
  type Inner = &'a Modifier;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Modifier>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Modifier {
  type Inner = &'a Modifier;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Modifier>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Modifier {
    type Output = Modifier;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const Modifier as *const u8, <Self as flatbuffers::Push>::size());
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> flatbuffers::Verifiable for Modifier {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Modifier {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    domain: ModifierDomain,
    func: ModifierFunc,
    operation: ModifierOperation,
    modified_attribute_id: i32,
    modifying_attribute_id: i32,
    group_id: i32,
    skill_type_id: i32,
  ) -> Self {
    let mut s = Self([0; 20]);
    s.set_domain(domain);
    s.set_func(func);
    s.set_operation(operation);
    s.set_modified_attribute_id(modified_attribute_id);
    s.set_modifying_attribute_id(modifying_attribute_id);
    s.set_group_id(group_id);
    s.set_skill_type_id(skill_type_id);
    s
  }

  pub fn domain(&self) -> ModifierDomain {
    let mut mem = core::mem::MaybeUninit::<<ModifierDomain as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<ModifierDomain as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_domain(&mut self, x: ModifierDomain) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<ModifierDomain as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn func(&self) -> ModifierFunc {
    let mut mem = core::mem::MaybeUninit::<<ModifierFunc as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[1..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<ModifierFunc as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_func(&mut self, x: ModifierFunc) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[1..].as_mut_ptr(),
        core::mem::size_of::<<ModifierFunc as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn operation(&self) -> ModifierOperation {
    let mut mem = core::mem::MaybeUninit::<<ModifierOperation as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[2..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<ModifierOperation as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_operation(&mut self, x: ModifierOperation) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[2..].as_mut_ptr(),
        core::mem::size_of::<<ModifierOperation as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn modified_attribute_id(&self) -> i32 {
    let mut mem = core::mem::MaybeUninit::<<i32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_modified_attribute_id(&mut self, x: i32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn modifying_attribute_id(&self) -> i32 {
    let mut mem = core::mem::MaybeUninit::<<i32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_modifying_attribute_id(&mut self, x: i32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn group_id(&self) -> i32 {
    let mut mem = core::mem::MaybeUninit::<<i32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[12..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_group_id(&mut self, x: i32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[12..].as_mut_ptr(),
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn skill_type_id(&self) -> i32 {
    let mut mem = core::mem::MaybeUninit::<<i32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[16..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_skill_type_id(&mut self, x: i32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[16..].as_mut_ptr(),
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct TypeDogmaAttribute, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct TypeDogmaAttribute(pub [u8; 8]);
impl Default for TypeDogmaAttribute { 
  fn default() -> Self { 
    Self([0; 8])
  }
}
impl core::fmt::Debug for TypeDogmaAttribute {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("TypeDogmaAttribute")
      .field("attribute_id", &self.attribute_id())
      .field("value", &self.value())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for TypeDogmaAttribute {}
impl<'a> flatbuffers::Follow<'a> for TypeDogmaAttribute {
  type Inner = &'a TypeDogmaAttribute;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a TypeDogmaAttribute>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a TypeDogmaAttribute {
  type Inner = &'a TypeDogmaAttribute;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<TypeDogmaAttribute>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for TypeDogmaAttribute {
    type Output = TypeDogmaAttribute;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const TypeDogmaAttribute as *const u8, <Self as flatbuffers::Push>::size());
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> flatbuffers::Verifiable for TypeDogmaAttribute {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> TypeDogmaAttribute {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    attribute_id: i32,
    value: f32,
  ) -> Self {
    let mut s = Self([0; 8]);
    s.set_attribute_id(attribute_id);
    s.set_value(value);
    s
  }

  pub fn attribute_id(&self) -> i32 {
    let mut mem = core::mem::MaybeUninit::<<i32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_attribute_id(&mut self, x: i32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn value(&self) -> f32 {
    let mut mem = core::mem::MaybeUninit::<<f32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_value(&mut self, x: f32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct TypeDogmaEffect, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct TypeDogmaEffect(pub [u8; 8]);
impl Default for TypeDogmaEffect { 
  fn default() -> Self { 
    Self([0; 8])
  }
}
impl core::fmt::Debug for TypeDogmaEffect {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("TypeDogmaEffect")
      .field("effect_id", &self.effect_id())
      .field("is_default", &self.is_default())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for TypeDogmaEffect {}
impl<'a> flatbuffers::Follow<'a> for TypeDogmaEffect {
  type Inner = &'a TypeDogmaEffect;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a TypeDogmaEffect>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a TypeDogmaEffect {
  type Inner = &'a TypeDogmaEffect;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<TypeDogmaEffect>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for TypeDogmaEffect {
    type Output = TypeDogmaEffect;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const TypeDogmaEffect as *const u8, <Self as flatbuffers::Push>::size());
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> flatbuffers::Verifiable for TypeDogmaEffect {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> TypeDogmaEffect {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    effect_id: i32,
    is_default: bool,
  ) -> Self {
    let mut s = Self([0; 8]);
    s.set_effect_id(effect_id);
    s.set_is_default(is_default);
    s
  }

  pub fn effect_id(&self) -> i32 {
    let mut mem = core::mem::MaybeUninit::<<i32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_effect_id(&mut self, x: i32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<i32 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn is_default(&self) -> bool {
    let mut mem = core::mem::MaybeUninit::<<bool as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<bool as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_is_default(&mut self, x: bool) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<<bool as EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum TypeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Type<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Type<'a> {
  type Inner = Type<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Type<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_NAME: flatbuffers::VOffsetT = 6;
  pub const VT_GROUP_ID: flatbuffers::VOffsetT = 8;
  pub const VT_CATEGORY_ID: flatbuffers::VOffsetT = 10;
  pub const VT_PUBLISHED: flatbuffers::VOffsetT = 12;
  pub const VT_FACTION_ID: flatbuffers::VOffsetT = 14;
  pub const VT_MARKET_GROUP_ID: flatbuffers::VOffsetT = 16;
  pub const VT_META_GROUP_ID: flatbuffers::VOffsetT = 18;
  pub const VT_RACE_ID: flatbuffers::VOffsetT = 20;
  pub const VT_CAPACITY: flatbuffers::VOffsetT = 22;
  pub const VT_MASS: flatbuffers::VOffsetT = 24;
  pub const VT_RADIUS: flatbuffers::VOffsetT = 26;
  pub const VT_VOLUME: flatbuffers::VOffsetT = 28;
  pub const VT_DOGMA_ATTRIBUTES: flatbuffers::VOffsetT = 30;
  pub const VT_DOGMA_EFFECTS: flatbuffers::VOffsetT = 32;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Type { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TypeArgs<'args>
  ) -> flatbuffers::WIPOffset<Type<'bldr>> {
    let mut builder = TypeBuilder::new(_fbb);
    if let Some(x) = args.dogma_effects { builder.add_dogma_effects(x); }
    if let Some(x) = args.dogma_attributes { builder.add_dogma_attributes(x); }
    if let Some(x) = args.volume { builder.add_volume(x); }
    if let Some(x) = args.radius { builder.add_radius(x); }
    if let Some(x) = args.mass { builder.add_mass(x); }
    if let Some(x) = args.capacity { builder.add_capacity(x); }
    builder.add_race_id(args.race_id);
    builder.add_meta_group_id(args.meta_group_id);
    builder.add_market_group_id(args.market_group_id);
    builder.add_faction_id(args.faction_id);
    builder.add_category_id(args.category_id);
    builder.add_group_id(args.group_id);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_id(args.id);
    builder.add_published(args.published);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Type::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn key_compare_less_than(&self, o: &Type) -> bool {
    self.id() < o.id()
  }

  #[inline]
  pub fn key_compare_with_value(&self, val: i32) -> ::core::cmp::Ordering {
    let key = self.id();
    key.cmp(&val)
  }
  /// English. The other languages live in the Names file.
  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Type::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn group_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Type::VT_GROUP_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn category_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Type::VT_CATEGORY_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn published(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Type::VT_PUBLISHED, Some(false)).unwrap()}
  }
  #[inline]
  pub fn faction_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Type::VT_FACTION_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn market_group_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Type::VT_MARKET_GROUP_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn meta_group_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Type::VT_META_GROUP_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn race_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Type::VT_RACE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn capacity(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Type::VT_CAPACITY, None)}
  }
  #[inline]
  pub fn mass(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Type::VT_MASS, None)}
  }
  #[inline]
  pub fn radius(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Type::VT_RADIUS, None)}
  }
  #[inline]
  pub fn volume(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Type::VT_VOLUME, None)}
  }
  #[inline]
  pub fn dogma_attributes(&self) -> Option<flatbuffers::Vector<'a, TypeDogmaAttribute>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, TypeDogmaAttribute>>>(Type::VT_DOGMA_ATTRIBUTES, None)}
  }
  #[inline]
  pub fn dogma_effects(&self) -> Option<flatbuffers::Vector<'a, TypeDogmaEffect>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, TypeDogmaEffect>>>(Type::VT_DOGMA_EFFECTS, None)}
  }
}

impl flatbuffers::Verifiable for Type<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<i32>("group_id", Self::VT_GROUP_ID, false)?
     .visit_field::<i32>("category_id", Self::VT_CATEGORY_ID, false)?
     .visit_field::<bool>("published", Self::VT_PUBLISHED, false)?
     .visit_field::<i32>("faction_id", Self::VT_FACTION_ID, false)?
     .visit_field::<i32>("market_group_id", Self::VT_MARKET_GROUP_ID, false)?
     .visit_field::<i32>("meta_group_id", Self::VT_META_GROUP_ID, false)?
     .visit_field::<i32>("race_id", Self::VT_RACE_ID, false)?
     .visit_field::<f32>("capacity", Self::VT_CAPACITY, false)?
     .visit_field::<f32>("mass", Self::VT_MASS, false)?
     .visit_field::<f32>("radius", Self::VT_RADIUS, false)?
     .visit_field::<f32>("volume", Self::VT_VOLUME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, TypeDogmaAttribute>>>("dogma_attributes", Self::VT_DOGMA_ATTRIBUTES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, TypeDogmaEffect>>>("dogma_effects", Self::VT_DOGMA_EFFECTS, false)?
     .finish();
    Ok(())
  }
}
pub struct TypeArgs<'a> {
    pub id: i32,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub group_id: i32,
    pub category_id: i32,
    pub published: bool,
    pub faction_id: i32,
    pub market_group_id: i32,
    pub meta_group_id: i32,
    pub race_id: i32,
    pub capacity: Option<f32>,
    pub mass: Option<f32>,
    pub radius: Option<f32>,
    pub volume: Option<f32>,
    pub dogma_attributes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, TypeDogmaAttribute>>>,
    pub dogma_effects: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, TypeDogmaEffect>>>,
}
impl<'a> Default for TypeArgs<'a> {
  #[inline]
  fn default() -> Self {
    TypeArgs {
      id: 0,
      name: None, // required field
      group_id: 0,
      category_id: 0,
      published: false,
      faction_id: 0,
      market_group_id: 0,
      meta_group_id: 0,
      race_id: 0,
      capacity: None,
      mass: None,
      radius: None,
      volume: None,
      dogma_attributes: None,
      dogma_effects: None,
    }
  }
}

pub struct TypeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TypeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: i32) {
    self.fbb_.push_slot::<i32>(Type::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Type::VT_NAME, name);
  }
  #[inline]
  pub fn add_group_id(&mut self, group_id: i32) {
    self.fbb_.push_slot::<i32>(Type::VT_GROUP_ID, group_id, 0);
  }
  #[inline]
  pub fn add_category_id(&mut self, category_id: i32) {
    self.fbb_.push_slot::<i32>(Type::VT_CATEGORY_ID, category_id, 0);
  }
  #[inline]
  pub fn add_published(&mut self, published: bool) {
    self.fbb_.push_slot::<bool>(Type::VT_PUBLISHED, published, false);
  }
  #[inline]
  pub fn add_faction_id(&mut self, faction_id: i32) {
    self.fbb_.push_slot::<i32>(Type::VT_FACTION_ID, faction_id, 0);
  }
  #[inline]
  pub fn add_market_group_id(&mut self, market_group_id: i32) {
    self.fbb_.push_slot::<i32>(Type::VT_MARKET_GROUP_ID, market_group_id, 0);
  }
  #[inline]
  pub fn add_meta_group_id(&mut self, meta_group_id: i32) {
    self.fbb_.push_slot::<i32>(Type::VT_META_GROUP_ID, meta_group_id, 0);
  }
  #[inline]
  pub fn add_race_id(&mut self, race_id: i32) {
    self.fbb_.push_slot::<i32>(Type::VT_RACE_ID, race_id, 0);
  }
  #[inline]
  pub fn add_capacity(&mut self, capacity: f32) {
    self.fbb_.push_slot_always::<f32>(Type::VT_CAPACITY, capacity);
  }
  #[inline]
  pub fn add_mass(&mut self, mass: f32) {
    self.fbb_.push_slot_always::<f32>(Type::VT_MASS, mass);
  }
  #[inline]
  pub fn add_radius(&mut self, radius: f32) {
    self.fbb_.push_slot_always::<f32>(Type::VT_RADIUS, radius);
  }
  #[inline]
  pub fn add_volume(&mut self, volume: f32) {
    self.fbb_.push_slot_always::<f32>(Type::VT_VOLUME, volume);
  }
  #[inline]
  pub fn add_dogma_attributes(&mut self, dogma_attributes: flatbuffers::WIPOffset<flatbuffers::Vector<'b , TypeDogmaAttribute>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Type::VT_DOGMA_ATTRIBUTES, dogma_attributes);
  }
  #[inline]
  pub fn add_dogma_effects(&mut self, dogma_effects: flatbuffers::WIPOffset<flatbuffers::Vector<'b , TypeDogmaEffect>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Type::VT_DOGMA_EFFECTS, dogma_effects);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TypeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TypeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Type<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Type::VT_NAME,"name");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Type<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Type");
      ds.field("id", &self.id());
      ds.field("name", &self.name());
      ds.field("group_id", &self.group_id());
      ds.field("category_id", &self.category_id());
      ds.field("published", &self.published());
      ds.field("faction_id", &self.faction_id());
      ds.field("market_group_id", &self.market_group_id());
      ds.field("meta_group_id", &self.meta_group_id());
      ds.field("race_id", &self.race_id());
      ds.field("capacity", &self.capacity());
      ds.field("mass", &self.mass());
      ds.field("radius", &self.radius());
      ds.field("volume", &self.volume());
      ds.field("dogma_attributes", &self.dogma_attributes());
      ds.field("dogma_effects", &self.dogma_effects());
      ds.finish()
  }
}
pub enum GroupOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Group<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Group<'a> {
  type Inner = Group<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Group<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_NAME: flatbuffers::VOffsetT = 6;
  pub const VT_CATEGORY_ID: flatbuffers::VOffsetT = 8;
  pub const VT_PUBLISHED: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Group { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GroupArgs<'args>
  ) -> flatbuffers::WIPOffset<Group<'bldr>> {
    let mut builder = GroupBuilder::new(_fbb);
    builder.add_category_id(args.category_id);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_id(args.id);
    builder.add_published(args.published);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Group::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn key_compare_less_than(&self, o: &Group) -> bool {
    self.id() < o.id()
  }

  #[inline]
  pub fn key_compare_with_value(&self, val: i32) -> ::core::cmp::Ordering {
    let key = self.id();
    key.cmp(&val)
  }
  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Group::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn category_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Group::VT_CATEGORY_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn published(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Group::VT_PUBLISHED, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Group<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<i32>("category_id", Self::VT_CATEGORY_ID, false)?
     .visit_field::<bool>("published", Self::VT_PUBLISHED, false)?
     .finish();
    Ok(())
  }
}
pub struct GroupArgs<'a> {
    pub id: i32,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub category_id: i32,
    pub published: bool,
}
impl<'a> Default for GroupArgs<'a> {
  #[inline]
  fn default() -> Self {
    GroupArgs {
      id: 0,
      name: None, // required field
      category_id: 0,
      published: false,
    }
  }
}

pub struct GroupBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> GroupBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: i32) {
    self.fbb_.push_slot::<i32>(Group::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Group::VT_NAME, name);
  }
  #[inline]
  pub fn add_category_id(&mut self, category_id: i32) {
    self.fbb_.push_slot::<i32>(Group::VT_CATEGORY_ID, category_id, 0);
  }
  #[inline]
  pub fn add_published(&mut self, published: bool) {
    self.fbb_.push_slot::<bool>(Group::VT_PUBLISHED, published, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> GroupBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GroupBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Group<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Group::VT_NAME,"name");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Group<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Group");
      ds.field("id", &self.id());
      ds.field("name", &self.name());
      ds.field("category_id", &self.category_id());
      ds.field("published", &self.published());
      ds.finish()
  }
}
pub enum CategoryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Category<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Category<'a> {
  type Inner = Category<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Category<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_NAME: flatbuffers::VOffsetT = 6;
  pub const VT_PUBLISHED: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Category { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CategoryArgs<'args>
  ) -> flatbuffers::WIPOffset<Category<'bldr>> {
    let mut builder = CategoryBuilder::new(_fbb);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_id(args.id);
    builder.add_published(args.published);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Category::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn key_compare_less_than(&self, o: &Category) -> bool {
    self.id() < o.id()
  }

  #[inline]
  pub fn key_compare_with_value(&self, val: i32) -> ::core::cmp::Ordering {
    let key = self.id();
    key.cmp(&val)
  }
  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Category::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn published(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Category::VT_PUBLISHED, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Category<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<bool>("published", Self::VT_PUBLISHED, false)?
     .finish();
    Ok(())
  }
}
pub struct CategoryArgs<'a> {
    pub id: i32,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub published: bool,
}
impl<'a> Default for CategoryArgs<'a> {
  #[inline]
  fn default() -> Self {
    CategoryArgs {
      id: 0,
      name: None, // required field
      published: false,
    }
  }
}

pub struct CategoryBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CategoryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: i32) {
    self.fbb_.push_slot::<i32>(Category::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Category::VT_NAME, name);
  }
  #[inline]
  pub fn add_published(&mut self, published: bool) {
    self.fbb_.push_slot::<bool>(Category::VT_PUBLISHED, published, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CategoryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CategoryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Category<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Category::VT_NAME,"name");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Category<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Category");
      ds.field("id", &self.id());
      ds.field("name", &self.name());
      ds.field("published", &self.published());
      ds.finish()
  }
}
pub enum DogmaAttributeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DogmaAttribute<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DogmaAttribute<'a> {
  type Inner = DogmaAttribute<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> DogmaAttribute<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_NAME: flatbuffers::VOffsetT = 6;
  pub const VT_DISPLAY_NAME: flatbuffers::VOffsetT = 8;
  pub const VT_DEFAULT_VALUE: flatbuffers::VOffsetT = 10;
  pub const VT_HIGH_IS_GOOD: flatbuffers::VOffsetT = 12;
  pub const VT_STACKABLE: flatbuffers::VOffsetT = 14;
  pub const VT_PUBLISHED: flatbuffers::VOffsetT = 16;
  pub const VT_UNIT_ID: flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DogmaAttribute { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DogmaAttributeArgs<'args>
  ) -> flatbuffers::WIPOffset<DogmaAttribute<'bldr>> {
    let mut builder = DogmaAttributeBuilder::new(_fbb);
    builder.add_unit_id(args.unit_id);
    builder.add_default_value(args.default_value);
    if let Some(x) = args.display_name { builder.add_display_name(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_id(args.id);
    builder.add_published(args.published);
    builder.add_stackable(args.stackable);
    builder.add_high_is_good(args.high_is_good);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DogmaAttribute::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn key_compare_less_than(&self, o: &DogmaAttribute) -> bool {
    self.id() < o.id()
  }

  #[inline]
  pub fn key_compare_with_value(&self, val: i32) -> ::core::cmp::Ordering {
    let key = self.id();
    key.cmp(&val)
  }
  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DogmaAttribute::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn display_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DogmaAttribute::VT_DISPLAY_NAME, None)}
  }
  #[inline]
  pub fn default_value(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(DogmaAttribute::VT_DEFAULT_VALUE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn high_is_good(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DogmaAttribute::VT_HIGH_IS_GOOD, Some(false)).unwrap()}
  }
  #[inline]
  pub fn stackable(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DogmaAttribute::VT_STACKABLE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn published(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DogmaAttribute::VT_PUBLISHED, Some(false)).unwrap()}
  }
  #[inline]
  pub fn unit_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DogmaAttribute::VT_UNIT_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for DogmaAttribute<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("display_name", Self::VT_DISPLAY_NAME, false)?
     .visit_field::<f32>("default_value", Self::VT_DEFAULT_VALUE, false)?
     .visit_field::<bool>("high_is_good", Self::VT_HIGH_IS_GOOD, false)?
     .visit_field::<bool>("stackable", Self::VT_STACKABLE, false)?
     .visit_field::<bool>("published", Self::VT_PUBLISHED, false)?
     .visit_field::<i32>("unit_id", Self::VT_UNIT_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct DogmaAttributeArgs<'a> {
    pub id: i32,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub display_name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub default_value: f32,
    pub high_is_good: bool,
    pub stackable: bool,
    pub published: bool,
    pub unit_id: i32,
}
impl<'a> Default for DogmaAttributeArgs<'a> {
  #[inline]
  fn default() -> Self {
    DogmaAttributeArgs {
      id: 0,
      name: None, // required field
      display_name: None,
      default_value: 0.0,
      high_is_good: false,
      stackable: false,
      published: false,
      unit_id: 0,
    }
  }
}

pub struct DogmaAttributeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> DogmaAttributeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: i32) {
    self.fbb_.push_slot::<i32>(DogmaAttribute::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DogmaAttribute::VT_NAME, name);
  }
  #[inline]
  pub fn add_display_name(&mut self, display_name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DogmaAttribute::VT_DISPLAY_NAME, display_name);
  }
  #[inline]
  pub fn add_default_value(&mut self, default_value: f32) {
    self.fbb_.push_slot::<f32>(DogmaAttribute::VT_DEFAULT_VALUE, default_value, 0.0);
  }
  #[inline]
  pub fn add_high_is_good(&mut self, high_is_good: bool) {
    self.fbb_.push_slot::<bool>(DogmaAttribute::VT_HIGH_IS_GOOD, high_is_good, false);
  }
  #[inline]
  pub fn add_stackable(&mut self, stackable: bool) {
    self.fbb_.push_slot::<bool>(DogmaAttribute::VT_STACKABLE, stackable, false);
  }
  #[inline]
  pub fn add_published(&mut self, published: bool) {
    self.fbb_.push_slot::<bool>(DogmaAttribute::VT_PUBLISHED, published, false);
  }
  #[inline]
  pub fn add_unit_id(&mut self, unit_id: i32) {
    self.fbb_.push_slot::<i32>(DogmaAttribute::VT_UNIT_ID, unit_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> DogmaAttributeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DogmaAttributeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DogmaAttribute<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, DogmaAttribute::VT_NAME,"name");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DogmaAttribute<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DogmaAttribute");
      ds.field("id", &self.id());
      ds.field("name", &self.name());
      ds.field("display_name", &self.display_name());
      ds.field("default_value", &self.default_value());
      ds.field("high_is_good", &self.high_is_good());
      ds.field("stackable", &self.stackable());
      ds.field("published", &self.published());
      ds.field("unit_id", &self.unit_id());
      ds.finish()
  }
}
pub enum DogmaEffectOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DogmaEffect<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DogmaEffect<'a> {
  type Inner = DogmaEffect<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> DogmaEffect<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_NAME: flatbuffers::VOffsetT = 6;
  pub const VT_DISPLAY_NAME: flatbuffers::VOffsetT = 8;
  pub const VT_EFFECT_CATEGORY: flatbuffers::VOffsetT = 10;
  pub const VT_PUBLISHED: flatbuffers::VOffsetT = 12;
  pub const VT_ELECTRONIC_CHANCE: flatbuffers::VOffsetT = 14;
  pub const VT_IS_ASSISTANCE: flatbuffers::VOffsetT = 16;
  pub const VT_IS_OFFENSIVE: flatbuffers::VOffsetT = 18;
  pub const VT_IS_WARP_SAFE: flatbuffers::VOffsetT = 20;
  pub const VT_PROPULSION_CHANCE: flatbuffers::VOffsetT = 22;
  pub const VT_RANGE_CHANCE: flatbuffers::VOffsetT = 24;
  pub const VT_DISALLOW_AUTO_REPEAT: flatbuffers::VOffsetT = 26;
  pub const VT_DISCHARGE_ATTRIBUTE_ID: flatbuffers::VOffsetT = 28;
  pub const VT_DURATION_ATTRIBUTE_ID: flatbuffers::VOffsetT = 30;
  pub const VT_FALLOFF_ATTRIBUTE_ID: flatbuffers::VOffsetT = 32;
  pub const VT_FITTING_USAGE_CHANCE_ATTRIBUTE_ID: flatbuffers::VOffsetT = 34;
  pub const VT_RANGE_ATTRIBUTE_ID: flatbuffers::VOffsetT = 36;
  pub const VT_RESISTANCE_ATTRIBUTE_ID: flatbuffers::VOffsetT = 38;
  pub const VT_TRACKING_SPEED_ATTRIBUTE_ID: flatbuffers::VOffsetT = 40;
  pub const VT_MODIFIERS: flatbuffers::VOffsetT = 42;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DogmaEffect { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DogmaEffectArgs<'args>
  ) -> flatbuffers::WIPOffset<DogmaEffect<'bldr>> {
    let mut builder = DogmaEffectBuilder::new(_fbb);
    if let Some(x) = args.modifiers { builder.add_modifiers(x); }
    builder.add_tracking_speed_attribute_id(args.tracking_speed_attribute_id);
    builder.add_resistance_attribute_id(args.resistance_attribute_id);
    builder.add_range_attribute_id(args.range_attribute_id);
    builder.add_fitting_usage_chance_attribute_id(args.fitting_usage_chance_attribute_id);
    builder.add_falloff_attribute_id(args.falloff_attribute_id);
    builder.add_duration_attribute_id(args.duration_attribute_id);
    builder.add_discharge_attribute_id(args.discharge_attribute_id);
    if let Some(x) = args.display_name { builder.add_display_name(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_id(args.id);
    builder.add_disallow_auto_repeat(args.disallow_auto_repeat);
    builder.add_range_chance(args.range_chance);
    builder.add_propulsion_chance(args.propulsion_chance);
    builder.add_is_warp_safe(args.is_warp_safe);
    builder.add_is_offensive(args.is_offensive);
    builder.add_is_assistance(args.is_assistance);
    builder.add_electronic_chance(args.electronic_chance);
    builder.add_published(args.published);
    builder.add_effect_category(args.effect_category);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DogmaEffect::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn key_compare_less_than(&self, o: &DogmaEffect) -> bool {
    self.id() < o.id()
  }

  #[inline]
  pub fn key_compare_with_value(&self, val: i32) -> ::core::cmp::Ordering {
    let key = self.id();
    key.cmp(&val)
  }
  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DogmaEffect::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn display_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DogmaEffect::VT_DISPLAY_NAME, None)}
  }
  #[inline]
  pub fn effect_category(&self) -> EffectCategory {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<EffectCategory>(DogmaEffect::VT_EFFECT_CATEGORY, Some(EffectCategory::Passive)).unwrap()}
  }
  #[inline]
  pub fn published(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DogmaEffect::VT_PUBLISHED, Some(false)).unwrap()}
  }
  #[inline]
  pub fn electronic_chance(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DogmaEffect::VT_ELECTRONIC_CHANCE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn is_assistance(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DogmaEffect::VT_IS_ASSISTANCE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn is_offensive(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DogmaEffect::VT_IS_OFFENSIVE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn is_warp_safe(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DogmaEffect::VT_IS_WARP_SAFE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn propulsion_chance(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DogmaEffect::VT_PROPULSION_CHANCE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn range_chance(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DogmaEffect::VT_RANGE_CHANCE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn disallow_auto_repeat(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DogmaEffect::VT_DISALLOW_AUTO_REPEAT, Some(false)).unwrap()}
  }
  #[inline]
  pub fn discharge_attribute_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DogmaEffect::VT_DISCHARGE_ATTRIBUTE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn duration_attribute_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DogmaEffect::VT_DURATION_ATTRIBUTE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn falloff_attribute_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DogmaEffect::VT_FALLOFF_ATTRIBUTE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn fitting_usage_chance_attribute_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DogmaEffect::VT_FITTING_USAGE_CHANCE_ATTRIBUTE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn range_attribute_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DogmaEffect::VT_RANGE_ATTRIBUTE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn resistance_attribute_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DogmaEffect::VT_RESISTANCE_ATTRIBUTE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn tracking_speed_attribute_id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DogmaEffect::VT_TRACKING_SPEED_ATTRIBUTE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn modifiers(&self) -> Option<flatbuffers::Vector<'a, Modifier>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Modifier>>>(DogmaEffect::VT_MODIFIERS, None)}
  }
}

impl flatbuffers::Verifiable for DogmaEffect<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("display_name", Self::VT_DISPLAY_NAME, false)?
     .visit_field::<EffectCategory>("effect_category", Self::VT_EFFECT_CATEGORY, false)?
     .visit_field::<bool>("published", Self::VT_PUBLISHED, false)?
     .visit_field::<bool>("electronic_chance", Self::VT_ELECTRONIC_CHANCE, false)?
     .visit_field::<bool>("is_assistance", Self::VT_IS_ASSISTANCE, false)?
     .visit_field::<bool>("is_offensive", Self::VT_IS_OFFENSIVE, false)?
     .visit_field::<bool>("is_warp_safe", Self::VT_IS_WARP_SAFE, false)?
     .visit_field::<bool>("propulsion_chance", Self::VT_PROPULSION_CHANCE, false)?
     .visit_field::<bool>("range_chance", Self::VT_RANGE_CHANCE, false)?
     .visit_field::<bool>("disallow_auto_repeat", Self::VT_DISALLOW_AUTO_REPEAT, false)?
     .visit_field::<i32>("discharge_attribute_id", Self::VT_DISCHARGE_ATTRIBUTE_ID, false)?
     .visit_field::<i32>("duration_attribute_id", Self::VT_DURATION_ATTRIBUTE_ID, false)?
     .visit_field::<i32>("falloff_attribute_id", Self::VT_FALLOFF_ATTRIBUTE_ID, false)?
     .visit_field::<i32>("fitting_usage_chance_attribute_id", Self::VT_FITTING_USAGE_CHANCE_ATTRIBUTE_ID, false)?
     .visit_field::<i32>("range_attribute_id", Self::VT_RANGE_ATTRIBUTE_ID, false)?
     .visit_field::<i32>("resistance_attribute_id", Self::VT_RESISTANCE_ATTRIBUTE_ID, false)?
     .visit_field::<i32>("tracking_speed_attribute_id", Self::VT_TRACKING_SPEED_ATTRIBUTE_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Modifier>>>("modifiers", Self::VT_MODIFIERS, false)?
     .finish();
    Ok(())
  }
}
pub struct DogmaEffectArgs<'a> {
    pub id: i32,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub display_name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub effect_category: EffectCategory,
    pub published: bool,
    pub electronic_chance: bool,
    pub is_assistance: bool,
    pub is_offensive: bool,
    pub is_warp_safe: bool,
    pub propulsion_chance: bool,
    pub range_chance: bool,
    pub disallow_auto_repeat: bool,
    pub discharge_attribute_id: i32,
    pub duration_attribute_id: i32,
    pub falloff_attribute_id: i32,
    pub fitting_usage_chance_attribute_id: i32,
    pub range_attribute_id: i32,
    pub resistance_attribute_id: i32,
    pub tracking_speed_attribute_id: i32,
    pub modifiers: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Modifier>>>,
}
impl<'a> Default for DogmaEffectArgs<'a> {
  #[inline]
  fn default() -> Self {
    DogmaEffectArgs {
      id: 0,
      name: None, // required field
      display_name: None,
      effect_category: EffectCategory::Passive,
      published: false,
      electronic_chance: false,
      is_assistance: false,
      is_offensive: false,
      is_warp_safe: false,
      propulsion_chance: false,
      range_chance: false,
      disallow_auto_repeat: false,
      discharge_attribute_id: 0,
      duration_attribute_id: 0,
      falloff_attribute_id: 0,
      fitting_usage_chance_attribute_id: 0,
      range_attribute_id: 0,
      resistance_attribute_id: 0,
      tracking_speed_attribute_id: 0,
      modifiers: None,
    }
  }
}

pub struct DogmaEffectBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> DogmaEffectBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: i32) {
    self.fbb_.push_slot::<i32>(DogmaEffect::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DogmaEffect::VT_NAME, name);
  }
  #[inline]
  pub fn add_display_name(&mut self, display_name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DogmaEffect::VT_DISPLAY_NAME, display_name);
  }
  #[inline]
  pub fn add_effect_category(&mut self, effect_category: EffectCategory) {
    self.fbb_.push_slot::<EffectCategory>(DogmaEffect::VT_EFFECT_CATEGORY, effect_category, EffectCategory::Passive);
  }
  #[inline]
  pub fn add_published(&mut self, published: bool) {
    self.fbb_.push_slot::<bool>(DogmaEffect::VT_PUBLISHED, published, false);
  }
  #[inline]
  pub fn add_electronic_chance(&mut self, electronic_chance: bool) {
    self.fbb_.push_slot::<bool>(DogmaEffect::VT_ELECTRONIC_CHANCE, electronic_chance, false);
  }
  #[inline]
  pub fn add_is_assistance(&mut self, is_assistance: bool) {
    self.fbb_.push_slot::<bool>(DogmaEffect::VT_IS_ASSISTANCE, is_assistance, false);
  }
  #[inline]
  pub fn add_is_offensive(&mut self, is_offensive: bool) {
    self.fbb_.push_slot::<bool>(DogmaEffect::VT_IS_OFFENSIVE, is_offensive, false);
  }
  #[inline]
  pub fn add_is_warp_safe(&mut self, is_warp_safe: bool) {
    self.fbb_.push_slot::<bool>(DogmaEffect::VT_IS_WARP_SAFE, is_warp_safe, false);
  }
  #[inline]
  pub fn add_propulsion_chance(&mut self, propulsion_chance: bool) {
    self.fbb_.push_slot::<bool>(DogmaEffect::VT_PROPULSION_CHANCE, propulsion_chance, false);
  }
  #[inline]
  pub fn add_range_chance(&mut self, range_chance: bool) {
    self.fbb_.push_slot::<bool>(DogmaEffect::VT_RANGE_CHANCE, range_chance, false);
  }
  #[inline]
  pub fn add_disallow_auto_repeat(&mut self, disallow_auto_repeat: bool) {
    self.fbb_.push_slot::<bool>(DogmaEffect::VT_DISALLOW_AUTO_REPEAT, disallow_auto_repeat, false);
  }
  #[inline]
  pub fn add_discharge_attribute_id(&mut self, discharge_attribute_id: i32) {
    self.fbb_.push_slot::<i32>(DogmaEffect::VT_DISCHARGE_ATTRIBUTE_ID, discharge_attribute_id, 0);
  }
  #[inline]
  pub fn add_duration_attribute_id(&mut self, duration_attribute_id: i32) {
    self.fbb_.push_slot::<i32>(DogmaEffect::VT_DURATION_ATTRIBUTE_ID, duration_attribute_id, 0);
  }
  #[inline]
  pub fn add_falloff_attribute_id(&mut self, falloff_attribute_id: i32) {
    self.fbb_.push_slot::<i32>(DogmaEffect::VT_FALLOFF_ATTRIBUTE_ID, falloff_attribute_id, 0);
  }
  #[inline]
  pub fn add_fitting_usage_chance_attribute_id(&mut self, fitting_usage_chance_attribute_id: i32) {
    self.fbb_.push_slot::<i32>(DogmaEffect::VT_FITTING_USAGE_CHANCE_ATTRIBUTE_ID, fitting_usage_chance_attribute_id, 0);
  }
  #[inline]
  pub fn add_range_attribute_id(&mut self, range_attribute_id: i32) {
    self.fbb_.push_slot::<i32>(DogmaEffect::VT_RANGE_ATTRIBUTE_ID, range_attribute_id, 0);
  }
  #[inline]
  pub fn add_resistance_attribute_id(&mut self, resistance_attribute_id: i32) {
    self.fbb_.push_slot::<i32>(DogmaEffect::VT_RESISTANCE_ATTRIBUTE_ID, resistance_attribute_id, 0);
  }
  #[inline]
  pub fn add_tracking_speed_attribute_id(&mut self, tracking_speed_attribute_id: i32) {
    self.fbb_.push_slot::<i32>(DogmaEffect::VT_TRACKING_SPEED_ATTRIBUTE_ID, tracking_speed_attribute_id, 0);
  }
  #[inline]
  pub fn add_modifiers(&mut self, modifiers: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Modifier>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DogmaEffect::VT_MODIFIERS, modifiers);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> DogmaEffectBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DogmaEffectBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DogmaEffect<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, DogmaEffect::VT_NAME,"name");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DogmaEffect<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DogmaEffect");
      ds.field("id", &self.id());
      ds.field("name", &self.name());
      ds.field("display_name", &self.display_name());
      ds.field("effect_category", &self.effect_category());
      ds.field("published", &self.published());
      ds.field("electronic_chance", &self.electronic_chance());
      ds.field("is_assistance", &self.is_assistance());
      ds.field("is_offensive", &self.is_offensive());
      ds.field("is_warp_safe", &self.is_warp_safe());
      ds.field("propulsion_chance", &self.propulsion_chance());
      ds.field("range_chance", &self.range_chance());
      ds.field("disallow_auto_repeat", &self.disallow_auto_repeat());
      ds.field("discharge_attribute_id", &self.discharge_attribute_id());
      ds.field("duration_attribute_id", &self.duration_attribute_id());
      ds.field("falloff_attribute_id", &self.falloff_attribute_id());
      ds.field("fitting_usage_chance_attribute_id", &self.fitting_usage_chance_attribute_id());
      ds.field("range_attribute_id", &self.range_attribute_id());
      ds.field("resistance_attribute_id", &self.resistance_attribute_id());
      ds.field("tracking_speed_attribute_id", &self.tracking_speed_attribute_id());
      ds.field("modifiers", &self.modifiers());
      ds.finish()
  }
}
pub enum SdeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Sde<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Sde<'a> {
  type Inner = Sde<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Sde<'a> {
  pub const VT_BUILD_NUMBER: flatbuffers::VOffsetT = 4;
  pub const VT_TYPES: flatbuffers::VOffsetT = 6;
  pub const VT_GROUPS: flatbuffers::VOffsetT = 8;
  pub const VT_CATEGORIES: flatbuffers::VOffsetT = 10;
  pub const VT_DOGMA_ATTRIBUTES: flatbuffers::VOffsetT = 12;
  pub const VT_DOGMA_EFFECTS: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Sde { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SdeArgs<'args>
  ) -> flatbuffers::WIPOffset<Sde<'bldr>> {
    let mut builder = SdeBuilder::new(_fbb);
    if let Some(x) = args.dogma_effects { builder.add_dogma_effects(x); }
    if let Some(x) = args.dogma_attributes { builder.add_dogma_attributes(x); }
    if let Some(x) = args.categories { builder.add_categories(x); }
    if let Some(x) = args.groups { builder.add_groups(x); }
    if let Some(x) = args.types { builder.add_types(x); }
    builder.add_build_number(args.build_number);
    builder.finish()
  }


  /// Build number of the SDE this was generated from.
  #[inline]
  pub fn build_number(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Sde::VT_BUILD_NUMBER, Some(0)).unwrap()}
  }
  #[inline]
  pub fn types(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Type<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Type>>>>(Sde::VT_TYPES, None)}
  }
  #[inline]
  pub fn groups(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Group<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Group>>>>(Sde::VT_GROUPS, None)}
  }
  #[inline]
  pub fn categories(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Category<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Category>>>>(Sde::VT_CATEGORIES, None)}
  }
  #[inline]
  pub fn dogma_attributes(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DogmaAttribute<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DogmaAttribute>>>>(Sde::VT_DOGMA_ATTRIBUTES, None)}
  }
  #[inline]
  pub fn dogma_effects(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DogmaEffect<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DogmaEffect>>>>(Sde::VT_DOGMA_EFFECTS, None)}
  }
}

impl flatbuffers::Verifiable for Sde<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("build_number", Self::VT_BUILD_NUMBER, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Type>>>>("types", Self::VT_TYPES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Group>>>>("groups", Self::VT_GROUPS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Category>>>>("categories", Self::VT_CATEGORIES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<DogmaAttribute>>>>("dogma_attributes", Self::VT_DOGMA_ATTRIBUTES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<DogmaEffect>>>>("dogma_effects", Self::VT_DOGMA_EFFECTS, false)?
     .finish();
    Ok(())
  }
}
pub struct SdeArgs<'a> {
    pub build_number: i32,
    pub types: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Type<'a>>>>>,
    pub groups: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Group<'a>>>>>,
    pub categories: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Category<'a>>>>>,
    pub dogma_attributes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DogmaAttribute<'a>>>>>,
    pub dogma_effects: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DogmaEffect<'a>>>>>,
}
impl<'a> Default for SdeArgs<'a> {
  #[inline]
  fn default() -> Self {
    SdeArgs {
      build_number: 0,
      types: None,
      groups: None,
      categories: None,
      dogma_attributes: None,
      dogma_effects: None,
    }
  }
}

pub struct SdeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SdeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_build_number(&mut self, build_number: i32) {
    self.fbb_.push_slot::<i32>(Sde::VT_BUILD_NUMBER, build_number, 0);
  }
  #[inline]
  pub fn add_types(&mut self, types: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Type<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Sde::VT_TYPES, types);
  }
  #[inline]
  pub fn add_groups(&mut self, groups: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Group<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Sde::VT_GROUPS, groups);
  }
  #[inline]
  pub fn add_categories(&mut self, categories: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Category<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Sde::VT_CATEGORIES, categories);
  }
  #[inline]
  pub fn add_dogma_attributes(&mut self, dogma_attributes: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<DogmaAttribute<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Sde::VT_DOGMA_ATTRIBUTES, dogma_attributes);
  }
  #[inline]
  pub fn add_dogma_effects(&mut self, dogma_effects: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<DogmaEffect<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Sde::VT_DOGMA_EFFECTS, dogma_effects);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SdeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SdeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Sde<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Sde<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Sde");
      ds.field("build_number", &self.build_number());
      ds.field("types", &self.types());
      ds.field("groups", &self.groups());
      ds.field("categories", &self.categories());
      ds.field("dogma_attributes", &self.dogma_attributes());
      ds.field("dogma_effects", &self.dogma_effects());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Sde`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_sde_unchecked`.
pub fn root_as_sde(buf: &[u8]) -> Result<Sde, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Sde>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Sde` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_sde_unchecked`.
pub fn size_prefixed_root_as_sde(buf: &[u8]) -> Result<Sde, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Sde>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Sde` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_sde_unchecked`.
pub fn root_as_sde_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Sde<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Sde<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Sde` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_sde_unchecked`.
pub fn size_prefixed_root_as_sde_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Sde<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Sde<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Sde and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Sde`.
pub unsafe fn root_as_sde_unchecked(buf: &[u8]) -> Sde {
  flatbuffers::root_unchecked::<Sde>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Sde and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Sde`.
pub unsafe fn size_prefixed_root_as_sde_unchecked(buf: &[u8]) -> Sde {
  flatbuffers::size_prefixed_root_unchecked::<Sde>(buf)
}
pub const SDE_IDENTIFIER: &str = "ESF1";

#[inline]
pub fn sde_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, SDE_IDENTIFIER, false)
}

#[inline]
pub fn sde_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, SDE_IDENTIFIER, true)
}

#[inline]
pub fn finish_sde_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Sde<'a>>) {
  fbb.finish(root, Some(SDE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_sde_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Sde<'a>>) {
  fbb.finish_size_prefixed(root, Some(SDE_IDENTIFIER));
}
}  // pub mod eve

