// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod eve {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum NamesOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Name lookup, in a file of its own.
///
/// An EFT-fit can be written in any of the eight languages EVE supports, so a
/// name has to be matchable back to a type.
pub struct Names<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Names<'a> {
  type Inner = Names<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Names<'a> {
  pub const VT_BUILD_NUMBER: flatbuffers::VOffsetT = 4;
  pub const VT_NAMES: flatbuffers::VOffsetT = 6;
  pub const VT_TYPE_IDS: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Names { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NamesArgs<'args>
  ) -> flatbuffers::WIPOffset<Names<'bldr>> {
    let mut builder = NamesBuilder::new(_fbb);
    if let Some(x) = args.type_ids { builder.add_type_ids(x); }
    if let Some(x) = args.names { builder.add_names(x); }
    builder.add_build_number(args.build_number);
    builder.finish()
  }


  #[inline]
  pub fn build_number(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Names::VT_BUILD_NUMBER, Some(0)).unwrap()}
  }
  /// Every name of every type, in every language, lowercased and sorted by
  /// UTF-8 bytes. Lowercasing is per code point and locale-independent, so
  /// that a fit does not have to match the case.
  #[inline]
  pub fn names(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>(Names::VT_NAMES, None).unwrap()}
  }
  #[inline]
  pub fn type_ids(&self) -> flatbuffers::Vector<'a, i32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i32>>>(Names::VT_TYPE_IDS, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for Names<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("build_number", Self::VT_BUILD_NUMBER, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>>>("names", Self::VT_NAMES, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i32>>>("type_ids", Self::VT_TYPE_IDS, true)?
     .finish();
    Ok(())
  }
}
pub struct NamesArgs<'a> {
    pub build_number: i32,
    pub names: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub type_ids: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i32>>>,
}
impl<'a> Default for NamesArgs<'a> {
  #[inline]
  fn default() -> Self {
    NamesArgs {
      build_number: 0,
      names: None, // required field
      type_ids: None, // required field
    }
  }
}

pub struct NamesBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NamesBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_build_number(&mut self, build_number: i32) {
    self.fbb_.push_slot::<i32>(Names::VT_BUILD_NUMBER, build_number, 0);
  }
  #[inline]
  pub fn add_names(&mut self, names: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Names::VT_NAMES, names);
  }
  #[inline]
  pub fn add_type_ids(&mut self, type_ids: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Names::VT_TYPE_IDS, type_ids);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NamesBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NamesBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Names<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Names::VT_NAMES,"names");
    self.fbb_.required(o, Names::VT_TYPE_IDS,"type_ids");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Names<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Names");
      ds.field("build_number", &self.build_number());
      ds.field("names", &self.names());
      ds.field("type_ids", &self.type_ids());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Names`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_names_unchecked`.
pub fn root_as_names(buf: &[u8]) -> Result<Names, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Names>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Names` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_names_unchecked`.
pub fn size_prefixed_root_as_names(buf: &[u8]) -> Result<Names, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Names>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Names` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_names_unchecked`.
pub fn root_as_names_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Names<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Names<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Names` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_names_unchecked`.
pub fn size_prefixed_root_as_names_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Names<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Names<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Names and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Names`.
pub unsafe fn root_as_names_unchecked(buf: &[u8]) -> Names {
  flatbuffers::root_unchecked::<Names>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Names and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Names`.
pub unsafe fn size_prefixed_root_as_names_unchecked(buf: &[u8]) -> Names {
  flatbuffers::size_prefixed_root_unchecked::<Names>(buf)
}
pub const NAMES_IDENTIFIER: &str = "ESFN";

#[inline]
pub fn names_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, NAMES_IDENTIFIER, false)
}

#[inline]
pub fn names_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, NAMES_IDENTIFIER, true)
}

#[inline]
pub fn finish_names_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Names<'a>>) {
  fbb.finish(root, Some(NAMES_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_names_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Names<'a>>) {
  fbb.finish_size_prefixed(root, Some(NAMES_IDENTIFIER));
}
}  // pub mod eve

