name: Release

on:
  release:
    types:
    - published

permissions:
  contents: read
  packages: write

jobs:
  registries:
    name: Publish to GitHub NPM
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Install Node toolchain
      uses: actions/setup-node@v7
      with:
        node-version: lts/*

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v2
      with:
        toolchain: stable

    - name: Install wasm-pack
      uses: taiki-e/install-action@v2
      with:
        tool: wasm-pack

    - name: Set version
      run: |
        # Remove the "v" from the version.
        VERSION=$(echo ${{ github.ref_name }} | cut -b2-)
        echo "Version: ${VERSION}"

        sed -i 's/version = "0.0.0-git"/version = "'${VERSION}'"/' Cargo.toml

    - name: Create NPM package
      run: |
        wasm-pack build --release -- --no-default-features --features wasm,eft
        sed -i s%esf-dogma-engine%@eveshipfit/dogma-engine% pkg/package.json

    - name: Publish to GitHub NPM
      uses: JS-DevTools/npm-publish@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        registry: "https://npm.pkg.github.com"
        package: pkg/package.json
