name: Release

on:
  release:
    types:
    - published

permissions:
  contents: read
  id-token: write

jobs:
  registries:
    name: Publish to NPM
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Install Node toolchain
      uses: actions/setup-node@v7
      with:
        node-version: lts/*
        registry-url: https://registry.npmjs.org

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v2
      with:
        toolchain: stable

    - name: Install wasm-pack
      uses: taiki-e/install-action@v2
      with:
        tool: wasm-pack

    - name: Set version
      run: |
        # Remove the "v" from the version.
        VERSION=$(echo ${{ github.ref_name }} | cut -b2-)
        echo "Version: ${VERSION}"

        sed -i 's/version = "0.0.0-git"/version = "'${VERSION}'"/' Cargo.toml

    - name: Create NPM package
      run: |
        wasm-pack build crates/esf-wasm --release --out-dir ../../pkg
        cp LICENSE pkg/
        sed -i 's%"name": "esf-wasm"%"name": "@eveshipfit/dogma-engine"%' pkg/package.json

    - name: Publish to NPM
      run: |
        npm publish ./pkg --access public
