name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v2
      with:
        toolchain: stable
        components: rustfmt, clippy
        target: wasm32-unknown-unknown

    - name: Install NodeJS
      uses: actions/setup-node@v7
      with:
        node-version: lts/*
        cache: npm

    - name: Install wasm-pack
      uses: taiki-e/install-action@v2
      with:
        tool: wasm-pack

    - name: Install NPM dependencies
      run: |
        npm ci

    - name: Install flatc
      # Keep in sync with the flatbuffers version in Cargo.toml.
      run: |
        curl -sSfL -o /tmp/flatc.zip https://github.com/google/flatbuffers/releases/download/v25.2.10/Linux.flatc.binary.g++-13.zip
        sudo unzip -o /tmp/flatc.zip -d /usr/local/bin
        flatc --version

    - name: Check generated code
      run: |
        flatc --rust --gen-onefile -o crates/esf-data/src/sde/ node_modules/@eveshipfit/sde/specs/eve.fbs node_modules/@eveshipfit/sde/specs/names.fbs
        git diff --exit-code

    - name: Build WASM library
      run: |
        wasm-pack build crates/esf-wasm --release --target web -- --locked

    - name: Build Rust binary
      run: |
        cargo build --release --locked -p esf-cli

    - name: Run tests
      run: |
        cargo test --locked --workspace

    - name: Check coding style
      run: |
        cargo fmt --check

    - name: Check lints
      run: |
        cargo clippy --locked --workspace --all-targets -- -D warnings
        cargo clippy --locked -p esf-wasm --all-targets --target wasm32-unknown-unknown -- -D warnings
