name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        registry-url: https://npm.pkg.github.com
        scope: "@eveshipfit"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Protobuf Compiler
      run: |
        sudo apt install -y --no-install-recommends protobuf-compiler

    - name: Install wasm-pack
      run: |
        cargo install wasm-pack

    - name: Build WASM library
      run: |
        wasm-pack build --release --target web -- --no-default-features --features wasm,eft

    - name: Build Rust binary
      run: |
        npm i
        cargo build --release --no-default-features --features rust,eft

    - name: Check coding style
      run: |
        cargo fmt --check
